### ISSUE TITLE
git tidy cannot detect branches merged using squash.

### ISSUE THREAD

**Issue by ehiggs** [drewwyatt/git-tidy#49]
There are a few common patterns of development. git tidy (probably) supports using merge commits when a PR is merged. Using this, it can see the hash of the commit and delete the local branches for the merged commits. At least, I think that's how it works.

However, many of us prefer (argument for another time) rebase+ff or squash merges (both supported by gitlab and github). Squash merging in particular can rewrite the hashes and confuse git tidy. It would be terrific if a solution was found for this.

**Comment by drewwyatt** [comment]
I'm surprised to read this, since squash merging is specifically the workflow that git-tidy was designed for. Can you elaborate on what you are seeing? 

When you squash you turn a lot of refs into a single ref, which can confuse some tools, and is why git-tidy doesn't use hashes to determine what to delete. `git-tidy` only targets refs that no longer have a remote ([regex here](https://github.com/drewwyatt/git-tidy/blob/e8097bd69b533a77683989371708779da9c14b17/src/git/mod.rs#L26)). So as long as you delete the branch after it has been squashed, `git-tidy` should notice it. 

Can you walk me through what you are seeing?

**Comment by ehiggs** [comment]
```
❯ git-tidy -V
git-tidy 2.0.1
```

I use `git tidy` on my work project and I still have:

```
❯ git tidy
  Nothing to do!
```

Expected: branches that were merged and deleted on the origin remote are now cleaned up and removed locally. However:

```
❯ git branch | wc -l
     434
```

Maybe confounding issues:
We use / in our branch names. But I have seen `git tidy` remove some of these branches but I don't understand how it sometimes works and other times doesn't work..

Also I have only a few heads locally that aren't on origin or remote:

```
❯ find .git/refs/heads -type f | grep -v origin | grep -v remote | wc -l
      10
```

I do not have a `.git/branches` directory.

I'm not sure where the discrepency is between not many heads in `.git/refs/heads` and many local branches still in `git branch`. Maybe some index needs to be rebuilt? 🤷

**Comment by alexfornuto** [comment]
I will also not instigate the argument over preferred methods, but say that on my newest repo I'm using the Rebase merge strategy, with GitHub auto-deleting the branch once it's merged, and I've got the same behavior of "nothing to do".

**Comment by drewwyatt** [comment]
@ehiggs / @alexfornuto Thank you for the info! 

Before I go into some suggestions I have (and a commitment to adding a `--debug` flag), can you confirm that the branches you are expecting to get "tidied up" have been deleted on the remote? Just in case there is a misunderstanding, for `git-tidy` to delete your local copies, they must no longer exist on the remote).

If they have have been: can you also confirm that your remote is called "origin" on your local machine (in writing up all of 👇 this, i realized that i have accidentally hardcoded that _very big_ assumption, and that might be what's clogging the pipes).

If you _have_ deleted the branches, AND your remote is called "origin", read on!

---

>  We use / in our branch names. But I have seen git tidy remove some of these branches but I don't understand how it sometimes works and other times doesn't work..

Yep, that definitely shouldn't be an issue

> I do not have a .git/branches directory.

I don't know enough about git internals to know if this is expected or not, but anecdotally none of my local repos have a branches directory in them either (my local branches _appear_ to be stored in `.git/refs/heads`).

> I'm not sure where the discrepency is between not many heads in .git/refs/heads and many local branches still in git branch. Maybe some index needs to be rebuilt? 🤷

So, this is (more or less) what `git-tidy` tries to do. I can walk you through those steps if you want to debug it, **but I can also commit to adding a `--debug` flag in the next couple of days** to see if that helps.

---

If you _want_ to try to debug this a bit more before then, [these are the commands `git-tidy` runs (in this order)](https://github.com/drewwyatt/git-tidy/blob/main/src/main.rs#L50) and what it's looking for:

1. `git fetch` ([implementation](https://github.com/drewwyatt/git-tidy/blob/main/src/git/models.rs#L49-L56) | [git docs](https://git-scm.com/docs/git-fetch)) -  makes sure you are in-sync with your remote (we don't do anything with the output, other than making sure it doesn't error)
2. `git remote prune origin` ([implementation](https://github.com/drewwyatt/git-tidy/blob/main/src/git/models.rs#L58-L69) | [git docs](https://git-scm.com/docs/git-remote#Documentation/git-remote.txt-empruneem)) - this forces git to remove local refs for remote branches that were deleted. **note: this won't delete your local branch if it wash squashed on the remote - because the hashes won't match anymore, so it won't be able to tell that it was merge** (_as an aside, i realize looking at this that `git-tidy` assumes here that your remote is named "origin"_ 😬) Like before, we don't do anything with the output other than make sure it didn't error.
3. `git branch -vv` ([implementation](https://github.com/drewwyatt/git-tidy/blob/main/src/git/models.rs#L71-L78) | [git docs](https://git-scm.com/docs/git-branch#Documentation/git-branch.txt--vv)) - this prints a "very verbose" branch listing

After getting the "very verbose" branch listing, we then check each of those branch names against [this regex](https://github.com/drewwyatt/git-tidy/blob/main/src/git/mod.rs#L26), where we are looking for output that looks like this: 

```
* main bc62e68 [origin/main: behind 1] init
  test fd1c2e4 [origin/test: gone] c
```

^ note that my "test" branch in that output says `:gone` (that's because the remote was deleted, but your local git can't tell _why_, because it was squashed) that's what the regex is looking for.

---

If you want to try running these commands yourself, let me know what you see, I'll drop an update here when I add a debug flag. Also, please let me know if you have any questions!

Thank you again for giving so much info and for taking the time to work with me on this issue. ❤️

**Comment by alexfornuto** [comment]
>Thank you again for giving so much info and for taking the time to work with me on this issue. heart

Thank *you* for being so communicative and willing to help! The usual response from OSS maintainers is to assume user error, so this is a refreshing change.

I'm going to provide screenshots and CLI output to confirm that we're talking about the same thing.

> can you confirm that the branches you are expecting to get "tidied up" have been deleted on the remote? 

```sh
❯ git branch
  ...
  main
  sitemap-ignore-examples
  ...
```

![image](https://user-images.githubusercontent.com/2349184/175036722-31c64dfe-76a5-49ba-b037-d5267ca81767.png)

> If they have have been: can you also confirm that your remote is called "origin" on your local machine

```sh
❯ git remote
origin
```

> I don't know enough about git internals to know if this is expected or not, but anecdotally none of my local repos have a branches directory in them either (my local branches appear to be stored in .git/refs/heads).

Same:

```sh
❯ ls .git
COMMIT_EDITMSG  description  filter-repo  hooks  info  objects    packed-refs
config          FETCH_HEAD   HEAD         index  logs  ORIG_HEAD  refs
```

> If you want to try to debug this a bit more before then, [these are the commands git-tidy runs (in this order)](https://github.com/drewwyatt/git-tidy/blob/main/src/main.rs#L50) and what it's looking for:

```sh
❯ git fetch
❯ git remote prune origin
❯ git branch -vv
  ...
* main                       0de4d6f exclude examples dir from sitemap
  sitemap-ignore-examples    684893d exclude examples dir from sitemap
  ...
```

So there's the discrepancy between what `git-tidy` expects and what git provides. I'm using what I think is the current version of git:

```sh
❯ git version
git version 2.36.1
```

I've been looking at the man page for `git branch` to see how to generate output matching your example, but have come up short so far.

**Comment by drewwyatt** [comment]
wooooooow. Okay. I.... don't know what to do with this information. 🤦 

FWIW, it looks like your version of git is newer than mine:

```zsh
$ git version
git version 2.32.0 (Apple Git-132)
```

 (let's hope that there is still something we can still key off of if what you are seeing is the new standard)

I'll do some digging and see what I can find. Thank you again!

**Comment by ehiggs** [comment]
> can you confirm that the branches you are expecting to get "tidied up" have been deleted on the remote?

Yes!

> can you also confirm that your remote is called "origin" on your local machine

Also yes. Good catch though.

---

```
❯ git --version
git version 2.36.1
```

> -v
> -vv
> --verbose
> When in list mode, show sha1 and commit subject line for each head, **along with relationship to upstream branch (if any)**. If given twice, print the path of the linked worktree (if any) and the name of the upstream branch, as well (see also git remote show <remote>). Note that the current worktree’s HEAD will not have its path printed (it will always be your current directory).

I think this is the issue. When rebase+ff or squash is used then the upstream master seems to have no relationship any more. For all of my branches, nothing is printed but the branchname, commitID, and the first line of the last commit as @alexfornuto showed. We can see this using `git branch --merged` and `git branch --no-merged`. I mean, otherwise I would just use `git branch --merged | xargs -n1 git branch -d` from the `master` branch for `git-tidy`. :)

**Comment by drewwyatt** [comment]
@ehiggs 

> When rebase+ff or squash is used then the upstream master seems to have no relationship any more

Yep, that's exactly right. That's why (so far) `git-tidy` has relied on the `-vv` output that "print[s] the path of the linked worktree (if any) and the name of the upstream branch". 

When you squash/delete on the remote (like I did when I produced the output I posted above), your local copy can't tell that the remote was merged, all it sees it that it no longer exists anymore. Which is why git (at least in some cases) represents this by showing `: gone`. e.g.

```
* main bc62e68 [origin/main: behind 1] init
  test fd1c2e4 [origin/test: gone] c
```

Are you able to share your output from `git branch -vv` after a squash/delete?

---

Edit: please, if you can, run `git fetch` / `git remote prune origin` first - either run them yourself or let `git-tidy` run them for you.

**Comment by drewwyatt** [comment]
@ehiggs @alexfornuto One other thought I just had:

Can you both confirm that the remote branch that you deleted was set as the upstream branch of your local _at some point_? e.g.

```
$ git add .
$ git commit -m 'these are some changes'
$ git push --set-upstream origin some-branch # <--
```

**Comment by ehiggs** [comment]
I have never explictly used `--set-upstream` as a flag to `git push`. I run `git push origin HEAD`.

`git branch -vv' has 442 branches; `git branch -vv | grep ' \[origin\/' | wc -l` has 8 branches. These are branches where I pulled from origin before working on them (testing colleagues' work, etc) and the only ones of these remaining are live. So I think you may be onto a smoking gun!

**Comment by alexfornuto** [comment]
I also don't explicitly set the upstream. I use the `ggpush` alias in oh-my-zsh, which runs `git push origin "$(git_current_branch)"`.

**Comment by drewwyatt** [comment]
@ehiggs @alexfornuto 

I think this is our issue! I believe the reason neither of you are having branches deleted is because your local `git` doesn't have long lived associations (and can't tell when stuff disappears). 

In order for `git-tidy` to work, you will need to set the upstream at least once before the branch is deleted. You can do that in (at least) 2 ways.

1. [By calling either `git branch -u <branchname>` or `git branch --set-upstream-to <branchname>`](https://git-scm.com/docs/git-branch#Documentation/git-branch.txt--ultupstreamgt)
2. [When `push`ing (with `-u` or `--set-upstream` like I mentioned above.)](https://git-scm.com/docs/git-push#Documentation/git-push.txt--u)

Unfortunately, `git-tidy` relies on upstream tracking branches to figure out what is safe to delete.

**Comment by alexfornuto** [comment]
Got it! I've updated my config (`~/.oh-my-zsh/custom` for future Googlers) with a new version of the alias:

```sh
alias ggpush='git push -u origin "$(git_current_branch)"'
```

I went and re-pushed one of my WIP branches with `ggpush`, and `git branch -vv` is now showing a tracking upstream:

```
* v18-shortdocs-cleanup      d499b87 [origin/v18-shortdocs-cleanup] remove periods from shortdocs
```

Hopefully my PR will be approved shortly and I can confirm successful local deletion.

**Comment by alexfornuto** [comment]
Tested on another branch that was approved, merged, and auto-deleted:

```
❯ gco auth-logs
Switched to branch 'auth-logs'

❯ git branch --set-upstream-to origin/auth-logs
branch 'auth-logs' set up to track 'origin/auth-logs'.
❯ gco main
Switched to branch 'main'
❯ git-tidy -i
✔ Stale branches · auth-logs
No branches were deleted.
Finished with errors:
  - auth-logs: error: The branch 'auth-logs' is not fully merged.
If you are sure you want to delete it, run 'git branch -D auth-logs'.

❯ git-tidy -if
✔ Stale branches · auth-logs
Branches deleted:
  - auth-logs
```

So as you can see, I need to pass the `-f` flag because git doesn't seem to think that the branch is merged, but since I know it is I'm confident using the flag.

Thanks for diagnosing this issue @drewwyatt!

**Comment by ehiggs** [comment]
@drewwyatt explained the source of the issue. Not sure there's anything to do here except future feature requests. 

Closing this ticket; but what would be the best next step?

**Comment by alexfornuto** [comment]
@ehiggs you could set an alias similar to what I've described above. I wrote it out in the context of ZSH and oh-my-zsh, but any modern `sh` compatible shell should accept aliases.

**Comment by drewwyatt** [comment]
@ehiggs @alexfornuto 

If it's desired, it would be pretty trivial to include a flag (i don't know what to call it yet) that would delete all local branches that do not have an exact branch on the remote.

Requiring a deleted/missing ("gone") upstream branch today prevents git-tidy from deleting local branches that have _never_ had a remote branch - i.e. have never been pushed.  But this could be an opt-in nuclear option if you are willing/looking to live dangerously.

**Comment by ehiggs** [comment]
@alexfornuto I'm old and am used to logging into random machines on a cluster and not carrying my dotfiles anywhere - so I don't have a habit of using aliases. I will just get in the muscle memory habit of using -u when pushing. :)

In terms of `git-tidy` though, I wonder if it can scan branches or settings to determine if they are not linked to local. Or if a 'deep mode' can be used which compares commit messages.

**Comment by ehiggs** [comment]
> delete all local branches that do not have an exact branch on the remote.

That sounds super dangerous. Any work I haven't pushed would be blown away. Anyone who doesn't use the `-u` flag would lose all their work.

**Comment by drewwyatt** [comment]
@ehiggs oh yeah - it's definitely dangerous. That's why it doesn't work like this. Just to clarify: I'm suggesting this is opt-in behavior (not the default).
